<a href="https://colab.research.google.com/github/Trexroy1010/Machiene-Learning-Projects/blob/main/LSTMRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import tensorflow as tf
print("TensorFlow Version:", tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
if len(tf.config.list_physical_devices('GPU')) > 0:
    print("GPU Devices:", tf.config.list_physical_devices('GPU'))

TensorFlow Version: 2.19.0
Num GPUs Available: 1
GPU Devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [39]:
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
sent = [
    'the glass of milk',
    'the cup of tea',
    'I am a good boy',
    'the glass of juice',
    'I am a good developer',
    'Understand the meaning of words',
    'your videos are goos'
]

In [41]:
sent

['the glass of milk',
 'the cup of tea',
 'I am a good boy',
 'the glass of juice',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are goos']

In [42]:
vocabulary_size = 500

In [43]:
onehot_repr = [one_hot(words, vocabulary_size) for words in sent]

In [44]:
onehot_repr

[[78, 219, 421, 111],
 [78, 435, 421, 380],
 [336, 106, 406, 345, 420],
 [78, 219, 421, 290],
 [336, 106, 406, 345, 270],
 [136, 78, 384, 421, 101],
 [265, 498, 153, 372]]

In [45]:
#to embedd a sentence wer need to have all of them the same amount of words, which is why we are gonna do padding, post and pre.


In [46]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [47]:
import numpy as np


In [48]:
sent_length = 8
#we assume that the maimum sentence length is 8

In [49]:
embeded_doc = pad_sequences(onehot_repr,padding='pre', maxlen=sent_length)
print(embeded_doc)
#pre padding adds the required number of zeros before your sentences or array in order to amke them of the same length, for post it will be added after the sentence

[[  0   0   0   0  78 219 421 111]
 [  0   0   0   0  78 435 421 380]
 [  0   0   0 336 106 406 345 420]
 [  0   0   0   0  78 219 421 290]
 [  0   0   0 336 106 406 345 270]
 [  0   0   0 136  78 384 421 101]
 [  0   0   0   0 265 498 153 372]]


In [50]:
#now we convert every value to vectors
#10 feature dimention
dim = 10

In [51]:
model = Sequential()
model.add(Embedding(vocabulary_size,10,input_length = sent_length))
model.compile('adam','mse')
#adam optimiser and mean square error loss function

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [52]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.predict(embeded_doc[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step


array([[ 0.02416224,  0.00924484, -0.03038291,  0.01709691,  0.02405841,
        -0.04313176,  0.04080135, -0.0275064 ,  0.00626898,  0.00528984],
       [ 0.02416224,  0.00924484, -0.03038291,  0.01709691,  0.02405841,
        -0.04313176,  0.04080135, -0.0275064 ,  0.00626898,  0.00528984],
       [ 0.02416224,  0.00924484, -0.03038291,  0.01709691,  0.02405841,
        -0.04313176,  0.04080135, -0.0275064 ,  0.00626898,  0.00528984],
       [ 0.02416224,  0.00924484, -0.03038291,  0.01709691,  0.02405841,
        -0.04313176,  0.04080135, -0.0275064 ,  0.00626898,  0.00528984],
       [ 0.04628048,  0.04819543,  0.03344237,  0.02311743, -0.0066568 ,
        -0.03149153, -0.01596291, -0.01323781,  0.01808708, -0.00808973],
       [-0.01439399,  0.02753698, -0.01445884,  0.02327036, -0.00082431,
         0.00522799,  0.027661  ,  0.04792384,  0.04797474, -0.01212472],
       [ 0.01742706,  0.03610262, -0.03482495, -0.0492611 , -0.01380608,
        -0.01545124, -0.01381781, -0.02579559

[-0.04719212,  0.02650965, -0.01282742, -0.03290919, -0.02124256,
        -0.04588982, -0.01510155,  0.01483608,  0.01468216,  0.04167557], represents 0, the padding value we added at the begiining, each 10 numbers on each array reppresents each lines/

In [54]:
#assignment
sentence = ["The world is a better place",
            "Marvel series is my favorite movie",
            "I like DC movies",
            "The cat is eating the food",
            "Tom and Jerry is my favorite movie",
            "Python is my favorite programming Language"]

In [55]:
onehot_encoding = [one_hot(words, vocabulary_size) for words in sentence]

In [56]:
onehot_encoding

[[78, 372, 109, 406, 359, 51],
 [331, 487, 109, 156, 378, 387],
 [336, 172, 421, 152],
 [78, 130, 109, 391, 78, 38],
 [11, 56, 236, 109, 156, 378, 387],
 [454, 109, 156, 378, 224, 461]]

In [60]:
sentence_length_max = 10
embeded_doc2 = pad_sequences(onehot_encoding,padding='pre', maxlen=sentence_length_max)
print(embeded_doc2)

[[  0   0   0   0  78 372 109 406 359  51]
 [  0   0   0   0 331 487 109 156 378 387]
 [  0   0   0   0   0   0 336 172 421 152]
 [  0   0   0   0  78 130 109 391  78  38]
 [  0   0   0  11  56 236 109 156 378 387]
 [  0   0   0   0 454 109 156 378 224 461]]


In [61]:
dimentions = 10
model = Sequential()
model.add(Embedding(vocabulary_size,10,input_length = sentence_length_max))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [62]:
model.predict(embeded_doc2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step


array([[[-0.03483992, -0.04251238, -0.02575568,  0.00796112,
         -0.03912268,  0.04616605, -0.00463507,  0.02381155,
          0.04622394,  0.01342703],
        [-0.03483992, -0.04251238, -0.02575568,  0.00796112,
         -0.03912268,  0.04616605, -0.00463507,  0.02381155,
          0.04622394,  0.01342703],
        [-0.03483992, -0.04251238, -0.02575568,  0.00796112,
         -0.03912268,  0.04616605, -0.00463507,  0.02381155,
          0.04622394,  0.01342703],
        [-0.03483992, -0.04251238, -0.02575568,  0.00796112,
         -0.03912268,  0.04616605, -0.00463507,  0.02381155,
          0.04622394,  0.01342703],
        [ 0.04036308,  0.00118702,  0.01739726,  0.00426097,
          0.01394546, -0.03161149,  0.01747653, -0.04898744,
         -0.01412336,  0.04394903],
        [-0.04254203, -0.00381836,  0.00937314,  0.04438777,
         -0.01973791,  0.0334834 ,  0.02364154,  0.01152766,
         -0.00074066,  0.01228545],
        [ 0.03178569,  0.00889397,  0.03034687,  0.0